Slides for the demo
tue-robotics/tue_docs pull request #2
Opened 2017-10-07 14:14 UTC by LarsJanssenTUe

2017-10-07 14:35 UTC, LarsJanssenTUe commented
[Presentation_TechUnited_AtHome_slides.pdf](https://github.com/tue-robotics/tue_docs/files/1364685/Presentation_TechUnited_AtHome_slides.pdf)

Hereby the pdf file

2017-10-24 18:16 UTC, jlunenburg requested changes
Somehow, you've copied the entire folder. I'd rather see your changes in the existing folder.

2017-10-24 18:16 UTC, jlunenburg commented on demo_tutorial/Presentation_TechUnited_AtHome_slides.tex
> +			\textbf{Middle Size League (MSL)}
Why start with MSL???

2017-10-24 18:16 UTC, jlunenburg commented on demo_tutorial/Presentation_TechUnited_AtHome_slides.tex
> +				\item 15 - 30 minutes battery power
More battery power!

2017-10-24 18:16 UTC, jlunenburg commented on demo_tutorial/Presentation_TechUnited_AtHome_slides.tex
> +	\begin{frame}\TechUnitedTitle{Omni-wheels}\TechUnitedShield{16_9_not_4_3}
Why the bread? These are TURTLE wheels

2017-10-24 18:16 UTC, jlunenburg commented on demo_tutorial/Presentation_TechUnited_AtHome_slides.tex
> +	\begin{frame}\TechUnitedTitle{'Seeing' the world}\TechUnitedShield{16_9_not_4_3}
- Kinect V1
- What does software-based mean?
- AMIGO is an acronym, use all-caps

2017-10-24 18:16 UTC, jlunenburg commented on demo_tutorial/Presentation_TechUnited_AtHome_slides.tex
> +						\item Moveable up and down
You might start with the arms. Torso extends the reach of the arms (moveable up and down: would be slightly inconvenient if it were only able to move up OR down)

2017-10-31 19:01 UTC, LarsJanssenTUe commented on demo_tutorial/Presentation_TechUnited_AtHome_slides.tex
> +			\textbf{Middle Size League (MSL)}
I start with MSL in the general introduction to be able to keep the @Home team in the spotlight during the rest of the slides

2017-11-04 15:24 UTC, merged